const episodeGroupsData = [
  {
    title: "All",
    isActive: true,
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
    ],
  },
  {
    title: "Business",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },      
    ],
  },
  {
    title: "Comedy",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },      
    ],
  },
  {
    title: "Education",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },      
    ],
  },
  {
    title: "Health",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
            {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },      
    ],
  },
  {
    title: "News",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },      
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
    ],
  },
  {
    title: "Tech",
    items: [
      {
        imgSrc: './src/assets/images/episodes-card/2.jpg',
        tags: ['automation', 'tech'],
        number: 'Eps. 5',
        title: 'Tesla Autopilot Controversy',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/3.jpg',
        tags: ['women’s rights'],
        number: 'Eps. 4',
        title: "Women's Rights? Is it alright?",
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/6.jpg',
        tags: ['mind-behaviour', 'health'],
        number: 'Eps. 1',
        title: 'Are you a Perplexed Mind avatar?',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
            {
        imgSrc: './src/assets/images/episodes-card/4.jpg',
        tags: ['self-esteem', 'health'],
        number: 'Eps. 3',
        title: 'How to Deal with Self–Confidence',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/1.jpg',
        tags: ['covid-19', 'health'],
        number: 'Eps. 6',
        title: 'Pandemic Becoming Endemic',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
      {
        imgSrc: './src/assets/images/episodes-card/5.jpg',
        tags: ['social class', 'social class'],
        number: 'Eps. 2',
        title: 'Type of Social Classes of People',
        href: './podcast',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio.',
        hosted: 'Hosted by: ',
        avatarSrc: [
          './src/assets/images/avatar/5.jpg',
          './src/assets/images/avatar/6.jpg',
        ],
      },
    ],
  },
];

export default episodeGroupsData;